### ISSUE TITLE
Не отображается история перемещений на карте

### ISSUE THREAD

**Issue by artbrayko** [mavrikkk/ha_routes#2]
Добрый день, Все сделал по инструкции. В боковой панели появилась кнопка route, нажимаю Ваша карта есть, но история перемещений сенсоров на карте не отображается, хотя в основной карте HA они появились. Так же в папку /config/custom_components/route/ сам добавился файл route_temp.html. Что может быть?

**Comment by Tombraider2006** [comment]
у меня есть догадка по этому поводу что дело в том что не считывает данные из базы. у меня в качестве базы данных используется mariadb и ошибка аналогична вашей.

**Comment by artbrayko** [comment]
Из всех имеющихся устройств (три компа и два смарта) только на одном отображаются сенсоры. Везде захожу в НА через Google Chrome.

**Comment by mavrikkk** [comment]
я даже по локалке захожу по доменному имени...проблем с отображением нет...притом для меня это даже без вариантов...ибо по ип у меня ha даже не откроется...так настроено...поэтому вашу проблему не наблюдал никогда...

**Comment by mavrikkk** [comment]
> не считывает данные из базы. у меня в качестве базы данных используется mariadb и ошибка аналогична вашей.

для считывания данных используется rest api самого HA...ему пофиг какая БД у вас

**Comment by Tombraider2006** [comment]
> > не считывает данные из базы. у меня в качестве базы данных используется mariadb и ошибка аналогична вашей.
> 
> для считывания данных используется rest api самого HA...ему пофиг какая БД у вас

все сделано по инструкции, сенсор отображается, изменения по нему есть в логах, на карте пусто.

**Comment by mavrikkk** [comment]
элемент history включен? запись сенсоров  в историю ведется?

**Comment by Tombraider2006** [comment]
> элемент history включен? запись сенсоров в историю ведется?

конечно. специально после Вашего молчания в несколько месяцев переустановил модуль через HACS переписал с нуля и датчик и аддон в конфигурационном файле и даже вышел погулять для изменения логов.  какие данные Вам предоставить для понимания?
configuration.yaml```
route:
   days: 10
   mindst: 1
   time_zone: '+03:00'
   token: !secret my_long_life_token
   devices:
     - sensor.tom

```
sensor.yaml
`#роуты
- platform: template
  sensors:
    tom:
      value_template: >-
          {{states.device_tracker.tombr.last_updated}}
      attribute_templates:
        latitude: >-
            {{state_attr('device_tracker.tombr','latitude')}}
        longitude: >-
            {{state_attr('device_tracker.tombr','longitude')}}`

**Comment by mavrikkk** [comment]
> специально после Вашего молчания в несколько месяцев

))))) я не думал, что кто то кроме меня этим пользуется... популярностью не пользовался этот модуль...я даже не заглядывал сюда... случайно обнаружил issue ... так что я не специально

**Comment by mavrikkk** [comment]
сейчас я покопаюсь в коде, вспомню, как что работает...

**Comment by Tombraider2006** [comment]
> сейчас я покопаюсь в коде, вспомню, как что работает...

кстати в описании модуля стоит отметить что он не запустится если нет 
`http:
   base_url:` в configuration.yaml

 я в свое время сильно споткнулся на этом пункте.
может поэтому он и не пользуется популярностью

**Comment by artbrayko** [comment]
Пару выпусков назад в HA в карте Map Card появился атрибут hours_to_show, где выставляешь в часах путь к предыдущим локациям. Я так понимаю это что-то подобное Вашему компоненту. Вы еще не сталкивались? Не сравнивали?

**Comment by mavrikkk** [comment]
сравнивал... их модуль проще... ничего не надо настраивать... но мне он не понравился... он соединяет абсолютно все точки... не подписывает ни время в точке, ни порядок точек... если ты долго был на одном месте, а гпс кидал тебя туда сюда, то вся эта каша будет на карте... читаемость никакая... мой модуль оставит только одну точку...собственно, сами попробуйте... дело 2 кликов...

**Comment by Tombraider2006** [comment]
при прочих равных модуль route гораздо интереснее. именно по точкам и таймстампам. плюс отсев расстояния смещения. осталось только запустить)

**Comment by artbrayko** [comment]
> Выяснил. Если заходить из вне на HA, сенсоры отображаются. Если по локалки, то нет. Как сделать чтоб и по локалке видно было?

Так нет мыслей по этому поводу?

**Comment by Tombraider2006** [comment]
> Так нет мыслей по этому поводу?

дайте человеку код вспомнить) у меня кстати нет разницы. карта пустая при всех вариантах. и через локалку и через инет.

**Comment by Tombraider2006** [comment]
было б еще неплохо сбоку иметь колонку с маркерами точек. у меня три точки на карте 2 4 и 5 (2 раза из дома выходил. ни первого ни третьего маркера не видно на карте) так как их закрыл 5 маркер домашний. вся идея с таймстампами теряется(

**Comment by mavrikkk** [comment]
> алилуйя.. у меня заработало.. был прописан base_url: неправильно. https с портом.

ну вот )) отлично!
сейчас добавлю в ридми, что это поле надо заполнить...а правильность заполнения надо смотреть в гайдлайнах самого HA, там везде вроде в примерах без порта )

**Comment by mavrikkk** [comment]
> сбоку иметь колонку с маркерами точек

реализуемо...запишу в to do

**Comment by mavrikkk** [comment]
> при прочих равных модуль route гораздо интереснее.

спасибо

**Comment by Tombraider2006** [comment]
> реализуемо...запишу в to do

тогда уж наглеть так наглеть, в окне где выбираем сенсор для отображения хотелось бы видеть не имя сенсора, а его friendly_name

**Comment by mavrikkk** [comment]
> при заходе через локалку не отображается трек.

проблема осталась? как проявляется? в адресном поле браузера адрес локальный? или глобальное днс имя?

**Comment by Tombraider2006** [comment]
> в адресном поле браузера адрес локальный?

при формате адреса https://myname.site/route равным переменной base_url все отображается и карта и трек. при заходе на эту же страницу в формате адреса http://192.168.1.100:8123/route  карта видна, но маркеры и линии на ней не отображаются.

**Comment by mavrikkk** [comment]
> при заходе на эту же страницу в формате адреса http://192.168.1.100:8123/route

а зачем вы так заходите? )) по имени - проще...и работает везде!

более того, если я попробую зайти в свой дом из локальной сети по ип адресу http://192.168.1.100:8123 он у меня вообще не откроется...так настроен HA...

в вашем случае трек строится не будет...ограничение js...можете щелкнуть правой кнопкой мышки по карте гденть...выбрать "просмотреть код"...перейти на страницу console...очистить ее для чистоты эксперимента (правой кнопкой мышки и выбрать clear). а потом выбрать любой день или любой объект (чтоб типа построился маршрут)...внимательно погуглить ошибку, которая вывалится в консоли

**Comment by mavrikkk** [comment]
очень кратко: нельзя так просто херачить с одного домена в другой (с точки зрения браузера это мультидоменный запрос...запрос с домена 192.168... на mysite.com)

**Comment by Tombraider2006** [comment]
> в вашем случае трек строится не будет...ограничение js...можете щелкнуть правой кнопкой мышки по карте гденть...выбрать "просмотреть код"...перейти на страницу console...очистить ее для чистоты эксперимента (правой кнопкой мышки и выбрать clear). а потом выбрать любой день или любой объект (чтоб типа построился маршрут)

(был заблокирован политикой CORS: Ответ на запрос предварительной проверки не прошел проверку контроля доступа: в запрошенном ресурсе отсутствует заголовок «Access-Control-Allow-Origin». Если непрозрачный ответ отвечает вашим потребностям, установите режим запроса «no-cors», чтобы получить ресурс с отключенным CORS.)  вот результат просмотра кода, так может стоит указать параметр no-cors :) не все же такие правильные как вы)

**Comment by mavrikkk** [comment]
> так может стоит указать параметр no-cors

копните глубже...где его ставить то надо )) и как это в HA делать ;)

**Comment by mavrikkk** [comment]
эксклюзиф для самых наглых...
1. теперь виртуальные сенсоры сами создаются...не нужно этого делать вручную! (выложу для всех)
2. имена подтягиваются из friendly_name ... выкладывать для всех не буду, так как мне не нравится постоянная запись на диск. В общем, пока HA полностью не загрузится статус любого устройства None...соответственно я не могу узнать friendly_name во время запуска и инициализации своего модуля...остается читать эти имена в методе update, который вызывается раз в минуту...так как вся логика (карта, списки, маршруты) написаны на js в файле route.html, то мне этот файл надо перезаписывать...соответственно получается, что файл каждую минуту будет перезаписываться...притом бесполезно...
если выдумаете идею получше - велкам...
вот сам модуль:

https://yadi.sk/d/LQuIyy-8Nmte5g

**Comment by Tombraider2006** [comment]
> эксклюзиф для самых наглых...

орнул) 
дай тебе Бог здоровья добрый человек!

**Comment by Tombraider2006** [comment]
> 2\. если выдумаете идею получше - велкам..

можно начать с простого, имя отличается от имени сенсора `sensor.` так может его просто обрезать ?

**Comment by mavrikkk** [comment]
> можно начать с простого, имя отличается от имени сенсора `sensor.` так может его просто обрезать ?

себе так и сделал...но это ж не тру...все слитно через нижнее подчеркивание...по англ...убирание слова sensor красоты не придает
