### ISSUE TITLE
ошибка конфига. 

### ISSUE THREAD

**Issue by Tombraider2006** [mavrikkk/ha_routes#3]
![2020-03-05_17-28-17](https://user-images.githubusercontent.com/59514540/75991649-d28bab80-5f07-11ea-96ad-6b40eb27be39.jpg)
![2020-03-05_17-28-01](https://user-images.githubusercontent.com/59514540/75991653-d3244200-5f07-11ea-8e1d-ddeac214825c.jpg)
![2020-03-05_17-25-18](https://user-images.githubusercontent.com/59514540/75991654-d3bcd880-5f07-11ea-9492-bbb870c3e342.jpg)
![2020-03-05_17-24-38](https://user-images.githubusercontent.com/59514540/75991656-d3bcd880-5f07-11ea-8913-60c3367508dc.jpg)

**Comment by nur76n** [comment]
интеграция подключается по http. Попробуй добавить такой конфиг с локальным адресом, у меня в этом была проблема 
http:
     base_url: http://192.168.0.7:8123

**Comment by Tombraider2006** [comment]
спасибо, помогло
