### ISSUE TITLE
некоректно работает после обновление 111.1 или 111.2 

### ISSUE THREAD

**Issue by Tombraider2006** [mavrikkk/ha_routes#4]
![2020-06-17_22-21-33](https://user-images.githubusercontent.com/59514540/84940745-f060d300-b0e8-11ea-90fc-b7e4ce2bbd15.jpg)
вот такая красота вместо модуля( аффтор. спасай....

**Comment by mavrikkk** [comment]
времени пока вообще нет...но я думаю все дело в том, что они убрали параметр base_url
позже исправлю

**Comment by mavrikkk** [comment]
проверяйте
