### ISSUE TITLE
Ошибка в логах homeassistant.helpers.entity

### ISSUE THREAD

**Issue by eratnik** [mavrikkk/ha_routes#8]
Просят сообщить автору, что и делаю. Лог ниже:
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 20 декабря 2021 г., 21:47:44 (2 occurrences)
Last logged: 20 декабря 2021 г., 21:47:44

Entity sensor.virtual_device_tracker_inna_poco (<class 'custom_components.route.sensor.GPSSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.virtual_device_tracker_mi_note_10_pro (<class 'custom_components.route.sensor.GPSSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by mavrikkk** [comment]
проверьте

**Comment by DIMMonchik** [comment]
После обновления ошибка исчезла. Спасибо!
