### ISSUE TITLE
Ошибка coudnt copy files

### ISSUE THREAD

**Issue by dvjeny** [mavrikkk/ha_routes#9]
Добрый день!

В логах ошибка coudnt copy files и интеграция не работает.

![image](https://user-images.githubusercontent.com/62212078/157944721-2725f57b-afc7-4ac3-a2a8-f1e40c16a386.png)

Как исправить?

**Comment by mavrikkk** [comment]
недостаточно прав для записи нужных файлов. если ставили папку копированием - то поправьте права

**Comment by mavrikkk** [comment]
надеюсь, помогло, молчание - знак согласия )
